### ISSUE TITLE
No such file or directory: 'outputs/wrapper/u2t_map_all/unseen_5_seed_0/synthetic.jsonl'

### ISSUE THREAD

**Issue by AADeLucia** [Cyn7hia/PAED#4]
When running `python trainer_finetune.py` I encounter this error

```python
Traceback (most recent call last):
  File "/home/ec2-user/PAED/trainer_finetune.py", line 732, in <module>
    main(
  File "/home/ec2-user/PAED/trainer_finetune.py", line 600, in main
    training(save_dir, path_model, data_name, split, logger)
  File "/home/ec2-user/PAED/trainer_finetune.py", line 436, in training
    train_vae = VAEData(path=save_dir, train_args=train_args, name='train', data_name=data_name, split=split)
  File "/home/ec2-user/PAED/dataset.py", line 86, in __init__
    self.get_vocab(path_in)
  File "/home/ec2-user/PAED/dataset.py", line 202, in get_vocab
    dataset = self.get_data(self.path, name)
  File "/home/ec2-user/PAED/dataset.py", line 170, in get_data
    data = wr_Dataset.load(str(path_in))
  File "/home/ec2-user/PAED/wrapper.py", line 57, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/wrapper/u2t_map_all/unseen_5_seed_0/synthetic.jsonl'
```

Is this data supposed to be created by the script or do I need to download a file?

Thanks.

**Comment by Cyn7hia** [comment]
> When running `python trainer_finetune.py` I encounter this error
> 
> ```python
> Traceback (most recent call last):
>   File "/home/ec2-user/PAED/trainer_finetune.py", line 732, in <module>
>     main(
>   File "/home/ec2-user/PAED/trainer_finetune.py", line 600, in main
>     training(save_dir, path_model, data_name, split, logger)
>   File "/home/ec2-user/PAED/trainer_finetune.py", line 436, in training
>     train_vae = VAEData(path=save_dir, train_args=train_args, name='train', data_name=data_name, split=split)
>   File "/home/ec2-user/PAED/dataset.py", line 86, in __init__
>     self.get_vocab(path_in)
>   File "/home/ec2-user/PAED/dataset.py", line 202, in get_vocab
>     dataset = self.get_data(self.path, name)
>   File "/home/ec2-user/PAED/dataset.py", line 170, in get_data
>     data = wr_Dataset.load(str(path_in))
>   File "/home/ec2-user/PAED/wrapper.py", line 57, in load
>     with open(path) as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'outputs/wrapper/u2t_map_all/unseen_5_seed_0/synthetic.jsonl'
> ```
> 
> Is this data supposed to be created by the script or do I need to download a file?
> 
> Thanks.

Hi, 
the file `trainer_finetune.py` has been updated to fix the mentioned error.

**Comment by AADeLucia** [comment]
Thank you, that part works now. Now I get

```
Traceback (most recent call last):
  File "/data/PAED/trainer_finetune.py", line 734, in <module>
    main(
  File "/data/PAED/trainer_finetune.py", line 602, in main
    training(save_dir, path_model, data_name, split, logger)
  File "/data/PAED/trainer_finetune.py", line 441, in training
    ext_dataloader_tr, _ = get_dataloader(['train_syn', save_dir, model_args, train_args, data_args, vae_args,
  File "/data/PAED/dataset.py", line 856, in get_dataloader
    data.initialize()
  File "/data/PAED/dataset.py", line 296, in initialize
    self.data = self.get_data(self.path_in, self.name)
  File "/data/PAED/dataset.py", line 417, in get_data
    data = wr_Dataset.load(str(path_in))
  File "/data/PAED/wrapper.py", line 57, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/data/splits/zero_rte/u2t_map_all/unseen_5_seed_0/train_syn.jsonl'
```

but I see you removed the `train_syn.jsonl` in a previous commit (https://github.com/SenticNet/PAED/commit/aae077ce262d7f38d52792617e25251ec041d46b) am I not supposed to need that file anymore?

**Comment by Cyn7hia** [comment]
> Thank you, that part works now. Now I get
> 
> ```
> Traceback (most recent call last):
>   File "/data/PAED/trainer_finetune.py", line 734, in <module>
>     main(
>   File "/data/PAED/trainer_finetune.py", line 602, in main
>     training(save_dir, path_model, data_name, split, logger)
>   File "/data/PAED/trainer_finetune.py", line 441, in training
>     ext_dataloader_tr, _ = get_dataloader(['train_syn', save_dir, model_args, train_args, data_args, vae_args,
>   File "/data/PAED/dataset.py", line 856, in get_dataloader
>     data.initialize()
>   File "/data/PAED/dataset.py", line 296, in initialize
>     self.data = self.get_data(self.path_in, self.name)
>   File "/data/PAED/dataset.py", line 417, in get_data
>     data = wr_Dataset.load(str(path_in))
>   File "/data/PAED/wrapper.py", line 57, in load
>     with open(path) as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'outputs/data/splits/zero_rte/u2t_map_all/unseen_5_seed_0/train_syn.jsonl'
> ```
> 
> but I see you removed the `train_syn.jsonl` in a previous commit ([SenticNet@aae077c](https://github.com/SenticNet/PAED/commit/aae077ce262d7f38d52792617e25251ec041d46b)) am I not supposed to need that file anymore?

Thanks for your question~ I revised the `"train_syn"` into `train` in the 441th line of `trainer_finetune.py`. 
Yes, we don't need that file anymore for this project.
